title: elmah.io changelog
description: What's new on elmah.io
url: "https://changelog.elmah.io"

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 20
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
