title: elmah.io changelog
description: New features, fixes, and improvements to elmah.io - AI-powered error logging and uptime monitoring for .NET.
url: "https://changelog.elmah.io"

markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed

paginate: 20
paginate_path: "/page/:num/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
